name: Go

on:
  push:
    branches: [ "main", "testci" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Check python version
      run: python3 --version

    - name: Check python version
      run: python --version

    - name: Start emulators
      run: ./scripts/run_emulators/run_emulators start

    - name: Are they running?
      run: ps aux

    - name: Build
      run: bazelisk test //perf/...

